### ISSUE TITLE
Allow override of contract directory

### ISSUE THREAD

**Issue by tayzlor** [ConsenSys/truffle#100]
Truffle seems to expect contracts in ```working_dir/contracts``` if I want to store my contracts elsewhere can I do that?

I tried setting - 

```
contracts: {
  "directory": "./different/sub/dir"
}
```
in truffle.json, but it doesn't get picked up properly when running truffle deploy. Am I going wrong or is there a patch required here?

**Comment by tayzlor** [comment]
Could do something like ( a bit less crude than this but....

```
     if (config.app.resolved.contracts != null) {
       config.contracts.directory = `${working_dir}/${config.app.resolved.contracts.directory}`;
     }
```

**Comment by tcoulter** [comment]
Hey @tayzlor, happy to figure out why the setting didn't work. That said, can I get a broader overview of why you need this? Knowing the use case would help significantly.

**Comment by lastperson** [comment]
Hi, I stumbled upon a similar problem.
I'm trying to do an import of a contract placed in a separate dir.
`import "./../myGitModule/contracts/MyContract.sol";`
And it is always fails. This will help a lot, cause when you starting to split contracts in different repos, and then using them with inheritance or as `Contract` type then it is pity to copy paste them all the time.

**Comment by tayzlor** [comment]
Racking my brains to remember but its similar to the above - I was building a Meteor app where I have a directory structure like app/server app/client i wanted to have a contracts in app/contracts (or something like that) but it was not possible.

**Comment by tcoulter** [comment]
@lastperson You *should* be able to import contracts outside of the `contracts` directory, but I've verified that's a bug. Solidity imports are relative to the contract, and due to an assumption that all contracts live in the `contracts` directory, Truffle's having trouble finding the contract source. 

I've written a bug for this here, and verified it on my own: https://github.com/ConsenSys/truffle/issues/141

For now, configuring the name of the contracts directory is a bigger feature that needs to be addresses after major structural changes (in the works). For housekeeping purposes I'm going to close this ticket, but know that having a more flexible file structure is something we're actively pursuing. 

Thanks!
