### ISSUE TITLE
Error deploying contract

### ISSUE THREAD

**Issue by BenjaminJornet** [ConsenSys/truffle#149]
Hi,

I want to deploy an Ethereum contract on testnet using Truffle.

After `$ truffle compile -e consensys-testnet` and `$ truffle build -e consensys-testnet`, I got : 
```
$ truffle deploy -e consensys-testnet
Using environment consensys-testnet.
No contracts updated; skipping compilation.
Collecting dependencies...
Error deploying contract:
undefined
Deploy failed. See above.
```

My solidity contract is located in the contracts folder.

Can someone help me please ?

**Comment by NellyWhadsDev** [comment]
I believe your error is due to you not having defined the "consensys-testnet" is in terms of the rpc host and port number. After you specify those you should be good to go.

**Comment by BenjaminJornet** [comment]
Thank you for your answer ! In the app.json file, should I replace 
`"rpc": {
"host" : "localhost",
"port": 8545
}`
by something like that : 
`"rpc": {
"host" : "consensys-testnet",
"port": 8545
}` ?

**Comment by tcoulter** [comment]
Hi Benjamin,

If you still have an app.json file, this means you're on a very old version
of Truffle. Can you try upgrading to the latest version? Although the
current version of Truffle is v1.0.0, these migration steps from v0.2.0 to
v0.3.0 should help.
https://github.com/ConsenSys/truffle/wiki/Migrating-from-v0.2.x-to-v0.3.0

Thanks!

**Comment by BenjaminJornet** [comment]
Hi, 

No I don't. truffle.js is generating the app.json file

**Comment by BenjaminJornet** [comment]
I already have upgraded to v1.0, I just can't figure out how to configure the environment to deploy the contract on the testnet.

**Comment by tcoulter** [comment]
Reading your configuration above, your `host` variable is improperly configured. `host` refers to an http host, and `consensus-testnet` doesn't exist (i.e., it's not consensus-testnet.com, etc.). You'll need to find a host running an Ethereum node connected to the consensys testnet in order to use that host. 

I'm going to close this as it's a configuration issue. Please see this documentation for more details: http://truffle.readthedocs.io/en/latest/advanced/configuration/

PS: Truffle 2.0 has been released. Please try it out!
