### ISSUE TITLE
Update web3 version

### ISSUE THREAD

**Issue by flyswatter** [ConsenSys/truffle#166]
Right now truffle seems to inject an old version of `web3` that lacks the `web3.eth.sign` method.

I know you're doing a rewrite right now, but just making sure the new version gets the update.

**Comment by tcoulter** [comment]
:+1: will add to the list.

**Comment by tcoulter** [comment]
@flyswatter Was this an issue in your tests or in your frontend? I've just bumped the web3 version to the latest (0.16.0) on Truffle's end, but this won't effect the frontend if you're using the default builder.

**Comment by flyswatter** [comment]
This was a problem in the frontend. `web3.eth.sign` was unavailable. Why wouldn't this change what it injects? When detecting web3, if you're just passing our provider to your Web3 object, you are providing that Web3 version, regardless of what we supply.

**Comment by tcoulter** [comment]
The `web3` within Truffle is different than the `web3` on your frontend. This is because Truffle's default builder is a separate project, and is decoupled from Truffle: https://github.com/ConsenSys/truffle-default-builder

The default builder will still need to update its version of web3 in order for `web3.eth.sign` to be available on the frontend. I created a new pull request here: https://github.com/ConsenSys/truffle-default-builder/issues/1

**Comment by tcoulter** [comment]
I'm going to close this one as this is an issue for the default builder.

**Comment by flyswatter** [comment]
Can I get a link to the default builder? Can we open an issue there?

**Comment by tcoulter** [comment]
I gave you one. And I did already. :) Here it is again. https://github.com/ConsenSys/truffle-default-builder/issues/1

**Comment by flyswatter** [comment]
Whoops, thanks!
