### ISSUE TITLE
MetaCoin example discrepancy?

### ISSUE THREAD

**Issue by TrySpace** [ConsenSys/truffle#168]
So I've deployed the example with `truffle init` on two machines. Both are connecting to the **same**  `testrpc`.

Now, when I open the index.html in `development` I would expect, since both examples are using `account[0]`, that the balance I would see would be the same..
But somehow each instance shows its own META amount, *not the same*?

To recreate this, don't fill in any address, and fill in any amount, this will subtract an amount from the `account` ID, and update the `META` amount you have..

Either this is a bug, or I'm fundamentally misunderstanding how ethereum works?

**Comment by TrySpace** [comment]
Secondly, when I try changing the `app.js` of one instance to use `account[1]`. It will show `0` meta, correct.
But I would expect when I transfer x amount of `META` from the other client (`account[0]`) to this second address, it should receive it? But this does not happen, or at least does not show up in the other account. It's still `0`
I **do** see the `testrpc` receiving a `et_sendTransaction` though..

**Comment by tcoulter** [comment]
Hi @TrySpace. I apologize for the late response. These types of issues are best asked on Truffle's Gitter, where it's very likely you'll get a quick response from the community: http://gitter.im/consensys/truffle If your problem is still unsolved, please discuss on Gitter or open a new ticket. Thanks!
