### ISSUE TITLE
[BUG] truffle classifies tests that should fail as passing

### ISSUE THREAD

**Issue by SethVgr** [ConsenSys/truffle#225]
@tcoulter 

# Checklist
- [done ] installed **truffle** and **testrpc**

```
# npm install -g truffle
# npm install -g testrpc
```

Created a directory and ran initialized truffle:

```
mkdir test_project
cd test_project
truffle init
```

Cleared the pregenerated contracts and tests:

`rm -r tests/* contracts/* build/*`

and kept only the **Migrations.sol** contract in directory **contracts/**:

```
contract Migrations {
  address public owner;

  // A function with the signature `last_completed_migration()`, returning a uint, is required.
  uint public last_completed_migration;

  modifier restricted() {
    if (msg.sender == owner) _
  }

  function Migrations() {
    owner = msg.sender;
  }

  // A function with the signature `setCompleted(uint)` is required.
  function setCompleted(uint completed) restricted {
    last_completed_migration = completed;
  }

  function upgrade(address new_address) restricted {
    Migrations upgraded = Migrations(new_address);
    upgraded.setCompleted(last_completed_migration);
  }
}
```

Added a minimalist contract (in directory **contracts/**) and test js (in directory **tests/**) file:

**C.sol**
```
contract C {
    
    address[] allowedClientAddrs;
    address[] controlAddrs;

    function initAddrsDbgTruffle() {

        if (controlAddrs.length == 0) {
            controlAddrs.push(0xace9110f62d55189abfde92892af8613fd40945f);
        }

        if (allowedClientAddrs.length == 0) {
            allowedClientAddrs.push(0x3034715388e6f306c691eceea993cebd8360cb92);
        }

        if (controlAddrs.length == 1 && allowedClientAddrs.length == 1) {
            return;
        }

        for (uint256 i = 0; i < controlAddrs.length; i++) {
            if (controlAddrs[i] == 0xace9110f62d55189abfde92892af8613fd40945f)
                return;
        }

        for (i = 0; i < allowedClientAddrs.length; i++) {
            if (allowedClientAddrs[i] == 0x3034715388e6f306c691eceea993cebd8360cb92)
                return;
        }

        controlAddrs.push(0xace9110f62d55189abfde92892af8613fd40945f);
        allowedClientAddrs.push(0x3034715388e6f306c691eceea993cebd8360cb92);
    }

    function testClientAddr(uint256 index) constant returns(address) {
        address stub;

        if (index >= allowedClientAddrs.length) {
            return stub;
        }

        return allowedClientAddrs[index];
    }

    function testControlAddr(uint256 index) constant returns(address) {
        address stub;

        if (index >= controlAddrs.length) {
            return stub;
        }

        return controlAddrs[index];
    }

}
```

**c.js**
```
contract('C', function(accounts) {
  it("[I] Initializing addresses", function() {
    var fileDistribution = FileDistribution.deployed();

    fileDistribution.initAddrsDbgTruffle({from:accounts[0],gas:400000000}).then(function() {
      fileDistribution.testClientAddr.call(0).then(function(clientAddress) {

	assert.equal(clientAddress, "This is a test", "[E] The expected client address does not match " + clientAddress);
        
        return fileDistribution.testControlAddr.call(0).then(function(controlAddress) {
		
		assert.equal(controlAddress, "0xca35b7d915458ef540ade6068dfe2f44e8fa733c", "[E] The expected control address does not match " + controlAddress);
        });
      });
      
    });
  });

});
```
I have a migration file 1_deploy_contracts.js in directory **migrations/**

```
module.exports = function(deployer) {
  deployer.deploy(FileDistribution);
};
```

Next, I ran 

```
truffle compile --compile-all
truffle migrate
truffle test
```
Everything seemed ok; the contracts are compiled and mined by **testrpc**. 

## System/environment

- OS: debian 8.3 Jessie x64, kernel version 3.16.0-4-amd64, virtual machine, running on VirtualBox, host machine Win7 x64, NAT network settings used

## Expected behaviour

**truffle** should have failed test:

`assert.equal(clientAddress, "This is a test", "[E] The expected client address does not match " + clientAddress);`

## Observed behaviour

Both tests are marked as valid even though the first test in the first assertion is clearly not a valid Ethereum address:

```
Contract: C
    ✓ [I] Initializing addresses (39ms)
```

Is truffle broken?

**Comment by elenadimitrova** [comment]
Maybe a duplicate to https://github.com/ConsenSys/truffle/issues/223

**Comment by tcoulter** [comment]
See this line in your test (c.js): 

```
it("[I] Initializing addresses", function() {
```

You're not passing a `done` callback to the function. When you don't do this, mocha -- the underlying test framework used by Truffle -- assumes your test is synchronous (i.e., doesn't make any asynchronous calls). However, your test makes many asynchronous calls, as shown by your nested callbacks. This means the `it()` function is going to complete before your asynchronous calls do, and mocha will consider it a success.

To ensure it doesn't happy, put a `done` callback within the function provided:

```
it("[I] Initializing addresses", function(done) {
```

Then call that `done` function in your mostly deeply nested function after all your asserts. Mocha will now know that your test is asynchronous, and won't try to evaluate the results of the test until the `done` function is called.

There is one other option here, which is to return a promise, and mocha will evaluate that promise without the need for a `done` callback. However, this method won't work with nested promise chains, as in your example above. I've rewritten your test to both a) return a promise, and b) resolve your nested promise chains into single chain such that mocha will be able to evaluate it. One aside: You're not catching any promise errors and so even if there was an error mocha wouldn't know about it. In the example above you don't need to, because mocha knows how to handle a returned promise. However, it's good practice to catch errors on promise chains using `.catch()` when using promises (i.e., this case is an exception). 

Updated c.js:
```javascript
contract('C', function(accounts) {
  it("[I] Initializing addresses", function() {
    var fileDistribution = FileDistribution.deployed();
      
    // This return returns the whole promise chain to Mocha.
    return fileDistribution.initAddrsDbgTruffle({from:accounts[0],gas:400000000}).then(function() {
      // This return returns another promise, to be evaluated and then passed to the next callback in the chain.
      return fileDistribution.testClientAddr.call(0);
    }).then(function(clientAddress) {
      assert.equal(clientAddress, "This is a test", "[E] The expected client address does not match " + clientAddress);

      // Return another promise, continuing the chain.
      return fileDistribution.testControlAddr.call(0);
    }).then(function(controlAddress) {
      assert.equal(controlAddress, "0xca35b7d915458ef540ade6068dfe2f44e8fa733c", "[E] The expected control address does not match " + controlAddress);
    });
  });

});
```

I'm going to close this ticket for housekeeping issues. If you're positive there's actually a bug here, and it's not a misuse of promises / mocha, please don't hesitate to write in. Thanks!

**Comment by SethVgr** [comment]
Thanks. I did manage to get it to work.
