### ISSUE TITLE
[ERROR INSTALLING] MY ERROR

### ISSUE THREAD

**Issue by emum8** [ConsenSys/truffle#249]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\EMU\AppData\Roaming\npm\node_modules\truffle\node_modules\scrypt\build\copied_files.vcxproj]
C:\Program Files(x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\EMU\AppData\Roaming\npm\node_modules\truffle\node_modules\scrypt\build\scrypt_wrapper.vcxproj]

**Comment by tcoulter** [comment]
Hi there. I recommend attempting to do what the error says:

> The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". 

A quick google shows you can get the Windows 8.1 SDK here: https://developer.microsoft.com/en-us/windows/downloads/windows-8-1-sdk

Going to close for housekeeping purposes. Since everyone's installation issues are a little different, especially on Windows, I recommend asking these style of questions in the Truffle gitter: https://gitter.im/ConsenSys/truffle

**Comment by emum8** [comment]
Ya I had already installed that with npm but will try the setup, thanks.

**Comment by emum8** [comment]
I thought that may have come with visual studio already but I will try it.
I also installed some build tools package with npm.

**Comment by tcoulter** [comment]
Ya, definitely interesting if it doesn't.
