### ISSUE TITLE
Get array from contract fails

### ISSUE THREAD

**Issue by felixwatts** [ConsenSys/truffle#318]
- [ x] I've asked for help in the [Truffle Gitter](http://gitter.im/Consensys/truffle) before filing this issue.

---------------------------

## Issue

It seems impossible to read an array from contract memory using truffle js api

## Steps to Reproduce

create a contract with a public array type field. For example 

bytes32[] public SomeData;

Try to use the generated getter method:

var contract = MyContract.deployed();   
contract.SomeData.call().then(function(someData)
{
 console.log(someData);
});

alternatively create your own getter method - the result is the same

## Expected Behavior

An array of items is logged to the browser console

## Actual Results

Unhandled exception in javascript execution

Unhandled rejection BigNumber Error: new BigNumber() not a number: [object Object]
    at raise (http://localhost:8080/app.js:43221:25)
    at http://localhost:8080/app.js:43209:33
    at new BigNumber (http://localhost:8080/app.js:42237:67)
    at new BigNumber (http://localhost:8080/app.js:42247:25)
    at toBigNumber (http://localhost:8080/app.js:37861:12)
    at Object.toTwosComplement (http://localhost:8080/app.js:37872:21)
    at SolidityTypeUInt.formatInputInt [as _inputFormatter] (http://localhost:8080/app.js:36570:38)
    at SolidityTypeUInt.SolidityType.encode (http://localhost:8080/app.js:37218:17)
    at http://localhost:8080/app.js:36327:29
    at Array.map (native)
    at SolidityCoder.encodeParams (http://localhost:8080/app.js:36326:34)
    at SolidityFunction.toPayload (http://localhost:8080/app.js:39606:52)
    at SolidityFunction.call (http://localhost:8080/app.js:39645:24)
    at http://localhost:8080/app.js:7047:14

## Environment

* Operating System: Ubuntu Xenial
* Truffle version: Truffle v3.0.0-4
* Ethereum client: testrpc
* node version: v6.9.2
* npm version: 3.10.9

**Comment by tyleryasaka** [comment]
I have run into the same issue.

**Comment by pwrstudio** [comment]
Encountering the same problem trying to return non-numeric data.

**Comment by marcosjbarroso82** [comment]
I got this answer from gitter and it seems to work:
mi variable is:
Member[] public members;

and from javascript I read it like this:
for(uint i = 0; i < members.length; i++) { //do something here }

this way I read one item at a time.

I hope it helps,

**Comment by tcoulter** [comment]
When you use a member variable like this:

```
bytes32[] public SomeData;
```

Solidity doesn't create a function called `SomeData` that returns an array. Instead it creates a function that takes in the array index and returns the value at that index. The generated function would look something like this:

```
function SomeData_getter(uint index) returns (bytes32) {
  return SomeData[index];
} 
```

The reason this is failing is because web3 is expecting you to pass in a parameter to your function when you run `contract.SomeData.call()` -- but you're not. It tries parsing null and fails.

Arguably the error message could be better here. Unfortunately this is currently how web3 processes it. 

I'm going to close this issue. Please create a new issue if you have questions.
