### ISSUE TITLE
Problems with current `master` branch.

### ISSUE THREAD

**Issue by flyswatter** [ConsenSys/truffle#69]
Right now if I install the current `master` branch globally, running any truffle command fails with this error:
```
❯ truffle init
TypeError: Path must be a string. Received undefined
  at assertPath (path.js:8:11)
  at Object.posix.join (path.js:479:5)
```

However, if I provide an environment argument, even in a valid truffle project, I get this error instead:
```
❯ truffle init --e development                                                                    
Couldn't find any suitable environment. Check environment configuration.
```

**Comment by alexfisher** [comment]
Same error here.

**Comment by alexfisher** [comment]
It looks like there might be an issue with a non-string path being sent to path.join.  I did a quick and dirty edit around line 168 of config.es6 and set config.environments.current.directory = "" and re-ran truffle init and it worked!

**Comment by flyswatter** [comment]
Oh awesome, thanks for the tip!

- Dan

**Comment by alexfisher** [comment]
After doing so much troubleshooting and installing/reinstalling node, nvm, and a bunch of other stuff I decided to totally remove it all and start fresh this morning and got much better results.

I totally reinstalled node (LTS v 4.2.4) and ensured it was installed in my home directory instead of globally as suggested here:

https://nodejs.org/en/blog/uncategorized/development-environment/

Then I ensured npm was also set to use my home directory (when the global -g option is passed to it) as mentioned here:

http://stackoverflow.com/questions/10081293/install-npm-into-home-directory-with-distribution-nodejs-package-ubuntu

Then, I installed truffle and had zero issues running "truffle list" and "truffle init".

Perhaps having used a mix of a global node install using sudo and non global stuff was causing the path and permission issues I was running into over the last couple days.  In any case, hopefully this helps anyone else that may have encountered similar issues.

Back to making my way through 101 Noob Into to Programming Dapps!

http://consensys.github.io/developers/articles/101-noob-intro/

**Comment by tcoulter** [comment]
Fixed in the latest master, which will soon be pushed to npm. Note that this is major version change (0.2.x -> 0.3.0), so it comes with changes to how your dapps are structured. You can see the migration instructions here: https://github.com/ConsenSys/truffle/wiki/Migrating-from-v0.2.x-to-v0.3.0

**Comment by flyswatter** [comment]
Awesome, thanks!  Can’t wait to rebase my ‘develop-mode’ work onto this, and see if I can get dev/test environments running on EtherSim!On Jan 6, 2016, at 2:50 PM, Tim Coulter <notifications@github.com> wrote:Fixed in the latest master, which will soon be pushed to npm. Note that this is major version change (0.2.x -> 0.3.0), so it comes with changes to how your dapps are structured. You can see the migration instructions here: https://github.com/ConsenSys/truffle/wiki/Migrating-from-v0.2.x-to-v0.3.0—Reply to this email directly or view it on GitHub.

**Comment by alexfisher** [comment]
Thanks Tim!

**Comment by bencxr** [comment]
To anyone else who still hits this - I had my NODE_ENV environment set to something else, and the truffle init command isn't initializing in that situation. So make sure you don't have it set.
